-- MySQL Script generated by MySQL Workbench
-- Sat Jul  1 17:16:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema canoe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema canoe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `canoe` DEFAULT CHARACTER SET utf8 ;
USE `canoe` ;

-- -----------------------------------------------------
-- Table `canoe`.`fund_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `canoe`.`fund_manager` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `canoe`.`fund`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `canoe`.`fund` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fund_manager_id` INT NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `start_year` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `fund_manager_id`),
  INDEX `fk_fund_fund_manager1_idx` (`fund_manager_id` ASC) VISIBLE,
  CONSTRAINT `fk_fund_fund_manager1`
    FOREIGN KEY (`fund_manager_id`)
    REFERENCES `canoe`.`fund_manager` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `canoe`.`alias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `canoe`.`alias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fund_id` INT NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`, `fund_id`),
  INDEX `fk_alias_fund1_idx` (`fund_id` ASC) VISIBLE,
  CONSTRAINT `fk_alias_fund1`
    FOREIGN KEY (`fund_id`)
    REFERENCES `canoe`.`fund` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `canoe`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `canoe`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `canoe`.`investment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `canoe`.`investment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fund_id` INT NOT NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`id`, `fund_id`, `company_id`),
  INDEX `fk_investments_fund1_idx` (`fund_id` ASC) VISIBLE,
  INDEX `fk_investments_company1_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_investments_fund1`
    FOREIGN KEY (`fund_id`)
    REFERENCES `canoe`.`fund` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_investments_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `canoe`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
